// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: ProductModel.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//商品模型
type ProductsModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProdId    int32   `protobuf:"varint,1,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty"`           // 商品ID
	ProdName  string  `protobuf:"bytes,2,opt,name=prod_name,json=prodName,proto3" json:"prod_name,omitempty"`      // 商品名称
	ProdDesc  string  `protobuf:"bytes,3,opt,name=prod_desc,json=prodDesc,proto3" json:"prod_desc,omitempty"`      // 商品描述
	ProdPrice float32 `protobuf:"fixed32,4,opt,name=prod_price,json=prodPrice,proto3" json:"prod_price,omitempty"` // 商品价格
}

func (x *ProductsModel) Reset() {
	*x = ProductsModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProductModel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductsModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsModel) ProtoMessage() {}

func (x *ProductsModel) ProtoReflect() protoreflect.Message {
	mi := &file_ProductModel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsModel.ProtoReflect.Descriptor instead.
func (*ProductsModel) Descriptor() ([]byte, []int) {
	return file_ProductModel_proto_rawDescGZIP(), []int{0}
}

func (x *ProductsModel) GetProdId() int32 {
	if x != nil {
		return x.ProdId
	}
	return 0
}

func (x *ProductsModel) GetProdName() string {
	if x != nil {
		return x.ProdName
	}
	return ""
}

func (x *ProductsModel) GetProdDesc() string {
	if x != nil {
		return x.ProdDesc
	}
	return ""
}

func (x *ProductsModel) GetProdPrice() float32 {
	if x != nil {
		return x.ProdPrice
	}
	return 0
}

var File_ProductModel_proto protoreflect.FileDescriptor

var file_ProductModel_proto_rawDesc = []byte{
	0x0a, 0x12, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x72, 0x6f,
	0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ProductModel_proto_rawDescOnce sync.Once
	file_ProductModel_proto_rawDescData = file_ProductModel_proto_rawDesc
)

func file_ProductModel_proto_rawDescGZIP() []byte {
	file_ProductModel_proto_rawDescOnce.Do(func() {
		file_ProductModel_proto_rawDescData = protoimpl.X.CompressGZIP(file_ProductModel_proto_rawDescData)
	})
	return file_ProductModel_proto_rawDescData
}

var file_ProductModel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ProductModel_proto_goTypes = []interface{}{
	(*ProductsModel)(nil), // 0: pb.ProductsModel
}
var file_ProductModel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ProductModel_proto_init() }
func file_ProductModel_proto_init() {
	if File_ProductModel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ProductModel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductsModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ProductModel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ProductModel_proto_goTypes,
		DependencyIndexes: file_ProductModel_proto_depIdxs,
		MessageInfos:      file_ProductModel_proto_msgTypes,
	}.Build()
	File_ProductModel_proto = out.File
	file_ProductModel_proto_rawDesc = nil
	file_ProductModel_proto_goTypes = nil
	file_ProductModel_proto_depIdxs = nil
}
